name: hello-world

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-22.04
    steps:
      - run: echo step 1, workflow 1
  job2:
    runs-on: ubuntu-22.04
    steps:
      - run: echo step 2, workflow 2
  job3:
      runs-on: ubuntu-22.04
      steps:
        - run: echo need jobs1 and 2
      needs:
        - job1
        - job2
