name: "variable hops"

on:
  workflow_dispatch:

jobs:
  job1
    runs-on: ubuntu-22.04
    steps:
      - name: first steps
        id: first-step
        run: |
          foo=bar
          echo "FOO=${foo}" >> "$GITHUB_ENV"

      - name: check
        run: echo $FOO

      
