name: "variable hops"

on:
  workflow_dispatch:

jobs:
  job1:
    steps:
      - name: step1
        id: step1
        run: |
          foo=bar
          echo "FOO=${foo}" >> "$GITHUB_ENV"

      - name: step2
        id: step2
        run: echo $FOO
